// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '******************',
    appId: '******************',
    messagingSenderId: '525811014450',
    projectId: 'sukhaphapthai-abc1b',
    authDomain: 'sukhaphapthai-abc1b.firebaseapp.com',
    storageBucket: 'sukhaphapthai-abc1b.firebasestorage.app',
    measurementId: 'G-531EF4NR3V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '******************',
    appId: '******************',
    messagingSenderId: '525811014450',
    projectId: 'sukhaphapthai-abc1b',
    storageBucket: 'sukhaphapthai-abc1b.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '*******************',
    appId: '******************',
    messagingSenderId: '525811014450',
    projectId: 'sukhaphapthai-abc1b',
    authDomain: 'sukhaphapthai-abc1b.firebaseapp.com',
    storageBucket: 'sukhaphapthai-abc1b.firebasestorage.app',
    measurementId: 'G-82DY6LGZG6',
  );
}
